### ISSUE TITLE
unexpected fault address 0xe7200000e72

### ISSUE THREAD

**Issue by foxconndmd** [andelf/go-curl#31]
遇到以下错误：
unexpected fault address 0xf8400472
throw: fault
[signal 0xb code=0x1 addr=0xf8400472 pc=0xf8400472b5]

goroutine 1 [running]:

goroutine 2 [syscall]:
created by runtime.main
	/home/michael/DPKG/golang/src/pkg/runtime/proc.c:221

goroutine 3 [timer goroutine (idle)]:
created by addtimer
	/home/michael/DPKG/golang/src/pkg/runtime/ztime_amd64.c:72
exit status 2

代码如下：
package main

import (
	curl "github.com/andelf/go-curl"
	"time"
)

func main() {
	fooTest := func(buf []byte, userdata interface{}) bool {
		println("DEBUG: size=>", len(buf))
		//println("DEBUG: content=>", string(buf))
		return true
	}
	mh := curl.MultiInit()
	for i := 0; i < 100; i++ {
		ch := curl.EasyInit()
		ch.Setopt(curl.OPT_URL, "http://www.baidu.com")
		ch.Setopt(curl.OPT_WRITEFUNCTION, fooTest)
		mh.AddHandle(ch)
	}
	for {
		nRunning, _ := mh.Perform()
		// println("n =", nRunning)
		if nRunning == 0 {
			println("ok")
			break
		}
		time.Sleep(1000)
	}
}

循环请求10次没问题，100次出现以上错误。
不使用回调ch.Setopt(curl.OPT_WRITEFUNCTION, fooTest)正常，使用后出现以上错误。

**Comment by foxconndmd** [comment]
解决了，没    defer ch.Cleanup()

**Comment by andelf** [comment]
:)
