### ISSUE TITLE
如何在windows上安装？

### ISSUE THREAD

**Issue by liyun2060** [andelf/go-curl#34]
试了好多次，不知道如何安装  也装了MINGW  然后编译完的libcurl文件不知道应该扔哪里

**Comment by andelf** [comment]
MinGW + MSYS 环境，默认configure libcurl 就可以，然后理论上应该有 pkg-config 可用
你详细贴下你的环境和错误我看看

**Comment by liyun2060** [comment]
e:/ms/src/github.com/andelf/go-curl/multi.go:199: undefined reference to `_imp__
curl_multi_timeout'
C:\Users\snail\AppData\Local\Temp\go-build733383814\github.com\andelf\go-curl\_o
bj\share.cgo2.o: In function `cgo_d7fcc9abd073_Cfunc_curl_share_cleanup':
e:/ms/src/github.com/andelf/go-curl/share.go:44: undefined reference to `_imp__c
url_share_cleanup'
C:\Users\snail\AppData\Local\Temp\go-build733383814\github.com\andelf\go-curl\_o
bj\share.cgo2.o: In function `cgo_d7fcc9abd073_Cfunc_curl_share_init':
e:/ms/src/github.com/andelf/go-curl/share.go:56: undefined reference to `_imp__c
url_share_init'
C:\Users\snail\AppData\Local\Temp\go-build733383814\github.com\andelf\go-curl\_o
bj\share.cgo2.o: In function `curl_share_setopt_long':
e:/ms/src/github.com/andelf/go-curl/share.go:7: undefined reference to `_imp__cu
rl_share_setopt'
C:\Users\snail\AppData\Local\Temp\go-build733383814\github.com\andelf\go-curl\_o
bj\share.cgo2.o: In function `curl_share_setopt_pointer':
e:/ms/src/github.com/andelf/go-curl/share.go:10: undefined reference to `_imp__c
url_share_setopt'
C:\Users\snail\AppData\Local\Temp\go-build733383814\github.com\andelf\go-curl\_o
bj\share.cgo2.o: In function `cgo_d7fcc9abd073_Cfunc_curl_share_strerror':
e:/ms/src/github.com/andelf/go-curl/share.go:99: undefined reference to `_imp__c
url_share_strerror'
collect2.exe: error: ld returned 1 exit status

上面是错误代码，我是拿到curl的源代码 make 然后生成了一些 curl.h之类的 ，放到mingw的目录  然后再go get  就出现这些错误了

**Comment by andelf** [comment]
............光有头文件不行，需要lib

**Comment by liyun2060** [comment]
lib也是有的，只是不知道应该放哪

**Comment by liyun2060** [comment]
还有就是pkg-config一直没找到可以下载的

**Comment by andelf** [comment]
你尽可能用 mingw 的installer，里面都有

**Comment by liyun2060** [comment]
支持https么？

**Comment by andelf** [comment]
应该是支持的

**Comment by liyun2060** [comment]
在curl源代码中  用mingw-make? 然后mingw-make install?

**Comment by liyun2060** [comment]
curl 官方说是 在根目录  mingw32-make mingw32
但是 我这样后并没有用

**Comment by andelf** [comment]
自己安装请参考其他教程啦。这个我这里教不了你。
曾经编译过全支持的curl，需要很长时间折腾。建议用成熟的。

**Comment by typenoob** [comment]
1. 安装msys2
2. 在msys2中用pacman安装curl
3. 指定`cgo_cflags=-IC:/msys64/mingw64/include -w`和`cgo_ldflags=-LC:/msys64/mingw64/lib -lcurl -lwldap32 -lws2_32`
