### ISSUE TITLE
How to return html of the page to variable?

### ISSUE THREAD

**Issue by pgamaster** [andelf/go-curl#37]
Sorry for a noob question. 
In php it is CURLOPT_RETURNTRANSFER, 1

How to return html of the page to variable using your lib?

**Comment by andelf** [comment]
CURLOPT_RETURNTRANSFER was invented by the PHP binding. :(
you can hava a look at [https://github.com/andelf/go-curl/blob/master/examples/channal_callback.go](examples/channal_callback.go).

**Comment by pgamaster** [comment]
thanks :)
