### ISSUE TITLE
Return HTTP status

### ISSUE THREAD

**Issue by jhnferraris** [andelf/go-curl#38]
Hello, I'm relatively new to Go and don't know on how to approach on debugging Go libraries.

My question is how do we log the HTTP Status (200, 400, 502) when using this library? The doc only shows how to get the response.

Thanks for the help!

**Comment by jhnferraris** [comment]
Update:

I saw this: `Getinfo(info)` method. How do you exactly use this? 

Thanks!

**Comment by andelf** [comment]
```go
		info, err := easy.Getinfo(curl.INFO_RESPONSE_CODE)
		if err == nil {
			print("code: ", info.(int))
		}
```

**Comment by jhnferraris** [comment]
Thanks!
