### ISSUE TITLE
大神，您好

### ISSUE THREAD

**Issue by dakunge** [andelf/go-curl#50]
我自己用go写了一个 客户端 测试性能，我的服务端什么都没做直接返回，用curl 测试性能比我用go写的快了一倍多，go上面开的goroutine 与 curl开的线程数是一样的，弄了好久也没找出问题来，而且客户端connection复用之类的都用上了，body每次用完也关闭了。弄了很久很久都没找出原因，快有3个月了，而且网上找了一些也没答案。我看您写这个了 想问问您知道我这个问题怎么回事吗？
  如果您需要我可以把完整代码发给您，这个问题我实在不知道怎么弄了。您能指点一下我吗？
  我的微信shanghaichaoren 期待您的回复，万分感谢，涕零顿首！！！

**Comment by andelf** [comment]
curl是纯C的吧，我猜及时加上调用cgo的开销，依然比go的goroutine要底层些？
你可以参考下go的其他高性能http client
