### ISSUE TITLE
Cannot compile after march 14 update

### ISSUE THREAD

**Issue by frozentech** [andelf/go-curl#67]
/go/src/github.com/andelf/go-curl/easy.go:408:22: identifier "_Ctype_struct_curl_slist" may conflict with identifiers generated by cgo

**Comment by rilutham** [comment]
I have the same issue with @frozentech

**Comment by frozentech** [comment]
Downgrade your go lang to 1.11.6. It works for me when I downgraded. I think the current go-curl does not work with 1.12

**Comment by rilutham** [comment]
Thanks @frozentech

**Comment by parkerlreed** [comment]
Any update on this? Downgrading a package doesnt seem like an ideal option

**Comment by vaneeswaran** [comment]
Till Go version 1.11.13 the issue is not seen. I guess the issue is introduced in **_1.12_**

**Comment by vaneeswaran** [comment]
Hi @Ullaakut, any updates on the issue.

**Comment by vaneeswaran** [comment]
Thanks  @Ullaakut

**Comment by kennkamau** [comment]
![Screenshot from 2020-05-25 07-34-36](https://user-images.githubusercontent.com/25039856/82778482-3912cc80-9e5a-11ea-99a5-af70135a85b1.png)

Problem still persist in 1.14

Details: 
ubuntu 19.10.
go 1.14
